Added rightTextprop to the picker select simple
reusejs/react pull request #150
Opened 2022-10-19 09:45 UTC by Subbu-betalectic

2022-10-19 10:57 UTC, rjvim commented on packages/react/src/molecules/pickers/select/base.tsx
> +            <LabelBase {...props.rightTextProps} />
@ShreyDhyani @Subbu-betalectic I don't think should be LabelBase right? This can be any component

2022-10-19 10:59 UTC, rjvim commented on packages/react/src/molecules/pickers/select/base.tsx
> +            <LabelBase {...props.rightTextProps} />
@Subbu-betalectic You need to just add something like 

```

<span className="cursor-pointer" onClick={() => setSelected([])}>
              <props.customRightComponent />
            </span>
```

2022-10-20 03:56 UTC, rjvim commented on packages/react/src/molecules/pickers/select/base.tsx
>            {props.clearComponent !== undefined &&
@Subbu-betalectic Need to also add customRightComponent to these conditions, else the UI might jerk

2022-10-20 04:05 UTC, ShreyDhyani commented on packages/react/src/atoms/labels/base.tsx
> +  onClick?: (e: any) => void;
@Subbu-betalectic pls try to give a better type than `any`. If you hover over the onclick function in label base you will be able to find the type of event `e` for eg `React.MouseEvent<HTMLElement>`

2022-10-20 04:07 UTC, ShreyDhyani commented on packages/react/src/molecules/pickers/select/base.tsx
> +  customRightComponent?: any;
Pls Use a better type.For example if it is a component then JSX.Element or React.ReactNode(if it can be string , number or other datatypes)

2022-10-20 04:08 UTC, ShreyDhyani requested changes

2022-10-20 04:08 UTC, ShreyDhyani commented on packages/react/src/atoms/labels/base.tsx
> +  onClick?: (e: any) => void;
Pls make these suggested changes.

2022-10-20 04:32 UTC, ShreyDhyani approved these changes

2022-10-20 04:32 UTC, merged